In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("data/influencers.csv", index_col="id")
df.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,MADRID,adrianramos,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,ALICANTE,sofiasantos,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129

In [5]:
df_filtrado = df.dropna()
df_filtrado.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,ALICANTE,sofiasantos,982.0,1822
183727,80's & friends! ✈️,158.0,40.0,22.0,MADRID,adrianramos,389.0,258

In [6]:
df_filtrado = df.fillna(0)
df_filtrado.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,MADRID,adrianramos,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,0.0,ALICANTE,sofiasantos,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129

Podemos indicar valores diferentes con fillna() para varias columnas

In [7]:
df_filtrado = df.fillna({ "retweets": 0, "mentions": -1 })
df_filtrado.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,MADRID,adrianramos,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,-1.0,ALICANTE,sofiasantos,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129

Podemos filtrar por campos.  Favoritos mayores a 400 y 20 menciones

In [8]:
df[  (df["favorites"] > 400) & (df["mentions"] > 20)]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183744,Thanks man!,430.0,143.0,28.0,ALICANTE,cristianoronaldo,NaN,351
183745,There is nothing better than programming!,424.0,110.0,29.0,ALICANTE,cristianoronaldo,82.0,351
183746,BORED AF,488.0,28.0,27.0,ELCHE,danicarvajal,21.0,2721